// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGZl_I9IuHxTj782oc8Ox542M-BCsyGzw',
    appId: '1:563128451824:web:95aac53d2d8f109f7af835',
    messagingSenderId: '563128451824',
    projectId: 'joecom-e54b3',
    authDomain: 'joecom-e54b3.firebaseapp.com',
    storageBucket: 'joecom-e54b3.appspot.com',
    measurementId: 'G-GP8MVQPH85',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoK-51Z3PQ4PH6k3TE6Bse0MhIYCXv1IA',
    appId: '1:563128451824:android:30dbb596a05a1b517af835',
    messagingSenderId: '563128451824',
    projectId: 'joecom-e54b3',
    storageBucket: 'joecom-e54b3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_s9IyqqR628pLZaB1aGRJ3s7I4F3dm_g',
    appId: '1:563128451824:ios:2afe212b01b266417af835',
    messagingSenderId: '563128451824',
    projectId: 'joecom-e54b3',
    storageBucket: 'joecom-e54b3.appspot.com',
    iosClientId: '563128451824-gpvv9a5fs2gfdca86ts0g99gnr7hllaq.apps.googleusercontent.com',
    iosBundleId: 'com.example.joEcom',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_s9IyqqR628pLZaB1aGRJ3s7I4F3dm_g',
    appId: '1:563128451824:ios:2afe212b01b266417af835',
    messagingSenderId: '563128451824',
    projectId: 'joecom-e54b3',
    storageBucket: 'joecom-e54b3.appspot.com',
    iosClientId: '563128451824-gpvv9a5fs2gfdca86ts0g99gnr7hllaq.apps.googleusercontent.com',
    iosBundleId: 'com.example.joEcom',
  );
}
